/**
 * Builds an inline SVG sprite from just the icons this site uses.
 *
 * Bootstrap Icons was loaded as a stylesheet from cdn.jsdelivr.net, which
 * pulled an entire icon webfont (~120 KB woff2 plus ~10 KB of CSS) from a
 * third-party origin to render around three dozen glyphs — and icon fonts
 * flash blank until the font lands.
 *
 * A sprite of the used icons is a few KB, inlines into the document, needs no
 * network request at all, and paints with the first frame.
 *
 *   node scripts/build-icons.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'src', 'components', 'IconSprite.astro');
const VERSION = '1.11.3';

/** Scan the source for every icon actually referenced. */
function collectIconNames() {
  const names = new Set();
  const walk = dir => {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const p = path.join(dir, entry.name);
      if (entry.isDirectory()) { walk(p); continue; }
      if (!/\.(astro|ts|js|mjs)$/.test(entry.name)) continue;
      const text = fs.readFileSync(p, 'utf8');
      for (const m of text.matchAll(/bi bi-([a-z0-9-]+)/g)) names.add(m[1]);
      for (const m of text.matchAll(/icon:\s*'bi-([a-z0-9-]+)'/g)) names.add(m[1]);
      for (const m of text.matchAll(/\bbi-([a-z0-9-]+)/g)) names.add(m[1]);
    }
  };
  walk(path.join(ROOT, 'src'));
  names.delete('');
  return [...names].sort();
}

const names = collectIconNames();
console.log(`icons referenced: ${names.length}`);

const symbols = [];
let fetched = 0, missing = [];

for (const name of names) {
  const url = `https://cdn.jsdelivr.net/npm/bootstrap-icons@${VERSION}/icons/${name}.svg`;
  const r = await fetch(url);
  if (!r.ok) { missing.push(name); continue; }
  const svg = await r.text();

  // Keep only the drawing instructions; the wrapper is replaced by <symbol>.
  const inner = svg
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/\s*<!--[\s\S]*?-->\s*/g, '')
    .trim();
  if (!inner) { missing.push(name); continue; }

  symbols.push(`  <symbol id="i-${name}" viewBox="0 0 16 16">${inner}</symbol>`);
  fetched++;
}

const file = `---
/**
 * Inline icon sprite — generated by scripts/build-icons.mjs, do not hand-edit.
 *
 * Replaces the Bootstrap Icons webfont, which cost a third-party connection
 * and a ~120 KB download to draw ${fetched} glyphs. Rendered once per page,
 * referenced with <Icon name="search" />.
 */
---
<svg xmlns="http://www.w3.org/2000/svg" style="display:none" aria-hidden="true" data-icon-sprite>
${symbols.join('\n')}
</svg>
`;

fs.writeFileSync(OUT, file);

const kb = fs.statSync(OUT).size / 1024;
console.log(`  fetched ${fetched}, missing ${missing.length}${missing.length ? ': ' + missing.join(', ') : ''}`);
console.log(`  sprite ${kb.toFixed(1)} KB -> src/components/IconSprite.astro`);
console.log(`  (replaces ~130 KB of third-party font + CSS)`);
