/**
 * Self-hosts the two brand typefaces.
 *
 * Google Fonts was loaded with a plain <link rel="stylesheet">, which is
 * render-blocking *and* third-party: the browser had to resolve DNS, connect
 * and TLS-handshake with fonts.googleapis.com, parse the returned CSS, then
 * start a second connection to fonts.gstatic.com before a single glyph could
 * paint. That is two extra round trips on the critical path of every page.
 *
 * Serving the woff2 files from our own origin removes both connections, and
 * lets us preload the exact files the first paint needs.
 *
 * Only the latin subset is kept — the site is English, and the cyrillic /
 * greek / vietnamese subsets Google also ships are dead weight here.
 *
 *   node scripts/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT_DIR = path.join(ROOT, 'public', 'fonts');
const CSS_OUT = path.join(ROOT, 'src', 'styles', 'fonts.css');

// A modern desktop UA, so Google serves woff2 rather than legacy formats.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Inter', spec: 'Inter:wght@400;500;600' },
  { name: 'Space Grotesk', spec: 'Space+Grotesk:wght@500;600;700' }
];

/** The latin block; anything else Google offers is unused here. */
const LATIN = 'U+0000-00FF';

fs.mkdirSync(OUT_DIR, { recursive: true });

const blocks = [];
let downloaded = 0, bytes = 0;

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.spec}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();

  // Each @font-face carries its own unicode-range; keep the latin ones.
  const faces = [...css.matchAll(/@font-face\s*\{([\s\S]*?)\}/g)].map(m => m[1]);

  /* Both families are variable fonts, so Google answers every weight in the
     request with the *same* file. Writing one file per weight shipped three
     byte-identical copies of Inter under different URLs, and the browser
     downloaded each separately. Group by source file instead and declare the
     weights it covers as a range. */
  const bySrc = new Map();
  for (const face of faces) {
    const range = (face.match(/unicode-range:\s*([^;]+);/) || [])[1] || '';
    if (!range.includes(LATIN)) continue;          // skip cyrillic/greek/vietnamese
    if (/latin-ext/.test(face)) continue;

    const family = (face.match(/font-family:\s*'([^']+)'/) || [])[1];
    const weight = Number((face.match(/font-weight:\s*(\d+)/) || [])[1]);
    const src = (face.match(/url\((https:[^)]+\.woff2)\)/) || [])[1];
    if (!family || !weight || !src) continue;

    if (!bySrc.has(src)) bySrc.set(src, { family, range: range.trim(), weights: [] });
    bySrc.get(src).weights.push(weight);
  }

  let n = 0;
  for (const [src, { family, range, weights }] of bySrc) {
    const lo = Math.min(...weights), hi = Math.max(...weights);
    const slug = family.toLowerCase().replace(/\s+/g, '-');
    const file = bySrc.size === 1 ? `${slug}.woff2` : `${slug}-${lo}${hi !== lo ? '-' + hi : ''}.woff2`;
    const buf = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    fs.writeFileSync(path.join(OUT_DIR, file), buf);
    downloaded++; bytes += buf.length; n++;

    blocks.push(
`@font-face {
  font-family: '${family}';
  font-style: normal;
  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};
  /* swap: show text immediately in the fallback rather than blocking paint */
  font-display: swap;
  src: url('/fonts/${file}') format('woff2');
  unicode-range: ${range};
}`
    );
    console.log(`  ${family} ${lo === hi ? lo : lo + '-' + hi}  ${(buf.length / 1024).toFixed(1)} KB  -> ${file}`);
  }
}

fs.writeFileSync(CSS_OUT,
`/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted so the first paint does not wait on two third-party
   connections (fonts.googleapis.com, then fonts.gstatic.com). */

${blocks.join('\n\n')}
`);

console.log(`\n${downloaded} files, ${(bytes / 1024).toFixed(0)} KB total -> public/fonts/`);
console.log(`wrote ${path.relative(ROOT, CSS_OUT)}`);
